// Types for our placeholder data
export interface Artwork {
  id: string;
  title: string;
  slug: string;
  year: number;
  description: string;
  medium: string;
  dimensions: string;
  imagePath: string;
  featured: boolean;
  category?: string; // Added to help with categorization
}

export interface Exhibition {
  id: string;
  title: string;
  venue: string;
  location: string;
  startDate: string;
  endDate: string;
  type: 'solo' | 'group';
  description: string;
}

export interface Photograph {
  id: string;
  title: string;
  slug: string;
  year: number;
  description: string;
  location: string;
  imagePath: string;
}

// Comprehensive Artworks Collection - Using actual file paths from public directory
export const artworks: Artwork[] = [
// Abstract Artworks 1990 - Present
  {
    id: '106',
    title: 'Composition 2025',
    slug: 'composition-2025',
    year: 2025,
    description: 'Three-dimensional work with balsa wooded slats on canvas. The main layout is determined by irregular porcupine quills elongated with straw reeds to obtain rectangular shapes. Includes 3 Persian miniatures (19th century), 3 carved wooden panels from Dutch standing watches, 9 original \'Cobra-like\' artworks from Björn T. Hansen (Danish, 1942-2007) and 9 Saul Steinberg landscapes (lithographs, Derriere le Miroir, Maeght Edition 1971). Also features tributes to Kurt Schwitters, Edgar P. Jacobs, Stéphane Heuet, and George Braque, along with Japanese prints, Coptic and Islamic handwritings, Soviet banknotes, a Venetian carnival mask, ethnographic items, fossils, and the artist\'s photographs from various locations.',
    medium: 'Mixed media with balsa wood slats on canvas',
    dimensions: '145 x 145 cm',
    imagePath: '/2025/composition_2025_140x145cm.png',
    featured: true,
    category: 'porcupine'
  },
  {
    id: '107',
    title: 'Composition 2024',
    slug: 'composition-2024',
    year: 2024,
    description: 'Three-dimensional artwork with pentagonal boxes made from balsa wood on canvas. This work is a further exploration of Composition no.2 – 2022 113x113 cm artwork. In the center, the height above the canvas surface is 10 cm. The boxes are created with open windows, causing specific shadowing dependent on the daylight situation. Inside the boxes, balsa wood slats are positioned in a specific \'rotating\' way. On top of the walls, tiny colored slats and arrows are placed. The slats inside the boxes are very slightly colored to allow the play of shadowing in this open structure.',
    medium: 'Balsa wood on canvas, three-dimensional',
    dimensions: '150 x 150 cm',
    imagePath: '/2024/Composition 2024 150x150cm.jpg',
    featured: true,
    category: 'abstract'
  },
  {
    id: '1',
    title: 'Composition No. 2 2022',
    slug: 'composition-no-2-2022',
    year: 2022,
    description: 'A sophisticated composition that continues the artist\'s investigation of geometric form and spatial relationships, featuring a balanced arrangement of shapes and colors.',
    medium: 'Mixed media on canvas',
    dimensions: '100 x 100 cm',
    imagePath: '/2022/10/Composition-no.2-29-sept-2022-om-14-1-scaled.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '2',
    title: 'Porcupine Boogie Woogie II',
    slug: 'porcupine-boogie-woogie-ii',
    year: 2022,
    description: 'A work inspired by the geometric abstraction of Mondrian\'s Boogie Woogie series, reinterpreted through the unique material properties of porcupine quills.',
    medium: 'Porcupine quills on panel',
    dimensions: '163 x 163 cm',
    imagePath: '/2022/03/Composition-2022-Procupine-Boogie-Woogie-II-scaled.jpg',
    featured: true,
    category: 'porcupine'
  },
  {
    id: '3',
    title: 'Porcupine Boogie Woogie I',
    slug: 'porcupine-boogie-woogie-i',
    year: 2021,
    description: 'The first in a series exploring the intersection of Mondrian\'s geometric principles with the textural qualities of porcupine quills, creating a unique tactile and visual experience.',
    medium: 'Porcupine quills on panel',
    dimensions: '113 x 113 cm',
    imagePath: '/2022/03/Porcupine-I-5-March-2021-finale-werk-2048x2039.jpg',
    featured: true,
    category: 'porcupine'
  },
  {
    id: '4',
    title: 'Composition 2018',
    slug: 'composition-2018',
    year: 2018,
    description: 'A contemporary geometric composition that builds on the artist\'s exploration of spatial relationships and color harmony, creating a dynamic visual field that rewards extended viewing.',
    medium: 'Acrylic on canvas',
    dimensions: '100 x 100 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Composition 2018, 100x100 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '5',
    title: 'Composition 2019 Different Speeds of Ageing',
    slug: 'composition-2019-different-speeds-of-ageing',
    year: 2019,
    description: 'A complex composition exploring the concept of time and aging through varied visual rhythms and textures, creating a meditation on the passage of time.',
    medium: 'Mixed media on canvas',
    dimensions: '113 x 113 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/2019 Composition 2019 Different speeds of ageing - 2.png',
    featured: false,
    category: 'abstract'
  },
  {
    id: '6',
    title: 'Composition 2017',
    slug: 'composition-2017',
    year: 2017,
    description: 'A bold geometric composition with overlapping forms creating a sense of depth and movement. The work explores color relationships and spatial tension.',
    medium: 'Mixed media on canvas',
    dimensions: '150 x 150 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Composition-2017, 150 x150 slider.jpg',
    featured: true,
    category: 'abstract'
  },
  {
    id: '7',
    title: 'Composition 2014',
    slug: 'composition-2014',
    year: 2014,
    description: 'A sophisticated geometric composition exploring spatial relationships and color harmony, with carefully balanced elements creating a meditative visual experience.',
    medium: 'Acrylic on canvas',
    dimensions: '100 x 100 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Composition 2014, 100 x 100 cm (2).jpg',
    featured: true,
    category: 'abstract'
  },
  {
    id: '8',
    title: 'Composition with Fixed Center',
    slug: 'composition-with-fixed-center',
    year: 1998,
    description: 'A structured composition built around a stable central focal point, with geometric elements radiating outward in a balanced arrangement. The work creates a sense of stability and order while maintaining visual interest through color variation and textural elements.',
    medium: 'Mixed media on canvas',
    dimensions: '100 x 100 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Composition with fixed center 1998, 100 x 100 cm.jpg',
    featured: true,
    category: 'abstract'
  },
  {
    id: '9',
    title: 'Composition 2007',
    slug: 'composition-2007',
    year: 2007,
    description: 'A refined geometric composition that demonstrates the artist\'s mature style, with a careful balance of form, color, and spatial relationships.',
    medium: 'Mixed media on canvas',
    dimensions: '40 x 50 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Composition 2007, 40 x 50 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '10',
    title: 'Composition with Open Structure',
    slug: 'composition-with-open-structure',
    year: 1999,
    description: 'A geometric abstraction featuring an open structure that creates a sense of space and movement across the canvas. The composition balances structured and spontaneous elements.',
    medium: 'Mixed media on canvas',
    dimensions: '150 x 150 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Composition with open structure 1999, 150 x 150 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '11',
    title: 'Composition II',
    slug: 'composition-ii-2004',
    year: 2004,
    description: 'A balanced geometric composition that explores spatial relationships through carefully arranged forms and a harmonious color palette.',
    medium: 'Mixed media',
    dimensions: '40 x 50 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Composition II 2004, 40 x 50 cm.png',
    featured: false,
    category: 'abstract'
  },
  {
    id: '12',
    title: 'Division of the Plane with Relief',
    slug: 'division-of-the-plane-with-relief',
    year: 1997,
    description: 'A textured composition that explores the division of space through relief elements, creating a dynamic interplay of light, shadow, and form.',
    medium: 'Mixed media with relief elements',
    dimensions: '65 x 65 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Division of the plane with relief 1997, 65 x 65 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '13',
    title: 'Disconnected Tiling Old and Modern',
    slug: 'disconnected-tiling-old-and-modern',
    year: 1997,
    description: 'A work that juxtaposes traditional and contemporary tiling patterns, creating a dialogue between historical and modern approaches to geometric abstraction.',
    medium: 'Mixed media on canvas',
    dimensions: '155 x 170 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Disconnected tiling, old and modern 1997, 155 x 170 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '14',
    title: 'Division of the Plane with Various Elements',
    slug: 'division-of-the-plane-with-various-elements',
    year: 1997,
    description: 'An abstract geometric composition exploring the division of a two-dimensional plane using various shapes, colors and textures. The work creates a visual rhythm through the careful arrangement of compositional elements.',
    medium: 'Mixed media on canvas',
    dimensions: '160 x 160 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Division of the plane with various elements 1997, 160 x 160 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '15',
    title: 'Division of the Plane No. I',
    slug: 'division-of-the-plane-no-i',
    year: 1997,
    description: 'A geometric study exploring the division of a two-dimensional plane through carefully arranged forms and a balanced color palette.',
    medium: 'Mixed media',
    dimensions: '55 x 57 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Division of the plane no. I 1997,-55 x 57 cm.png',
    featured: false,
    category: 'abstract'
  },
  {
    id: '16',
    title: 'Division of the Plane No. II',
    slug: 'division-of-the-plane-no-ii',
    year: 1997,
    description: 'A continuation of the artist\'s exploration of spatial division, with a different approach to form and color than its companion piece.',
    medium: 'Mixed media',
    dimensions: '58 x 42 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Division of the plane no. II 1997, 58 x 42 cm.png',
    featured: false,
    category: 'abstract'
  },
  {
    id: '17',
    title: 'Composition Based on Typed Papers',
    slug: 'composition-based-on-typed-papers',
    year: 1997,
    description: 'A mixed media composition that incorporates typed text as a visual element, creating a dialogue between language and abstract form.',
    medium: 'Mixed media with typed papers',
    dimensions: '115 x 80 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Composition based on typed papers 1997, 115 x 80 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '18',
    title: 'Disconnected Coptic Tiling',
    slug: 'disconnected-coptic-tiling',
    year: 1996,
    description: 'A composition inspired by Coptic visual traditions, featuring a pattern of disconnected tiles that create a rhythmic abstraction of space and form.',
    medium: 'Mixed media on canvas',
    dimensions: '150 x 150 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Disconnected Coptic tiling 1996, 150 x 150 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '19',
    title: 'Disconnected Tiling No. 1',
    slug: 'disconnected-tiling-no-1',
    year: 1996,
    description: 'A geometric composition featuring disconnected tiling patterns that create a dynamic visual rhythm across the canvas.',
    medium: 'Mixed media on canvas',
    dimensions: '100 x 100 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Disconnected tiling no.1 1996, 100 x 100.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '20',
    title: 'Disconnected Tiling No. 2',
    slug: 'disconnected-tiling-no-2',
    year: 1996,
    description: 'A continuation of the artist\'s exploration of disconnected tiling patterns, with a different scale and compositional approach than its companion piece.',
    medium: 'Mixed media on canvas',
    dimensions: '75 x 80 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Disconnected tiling no. 2 1996, 75 x 80 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '21',
    title: 'Expanding Tiling',
    slug: 'expanding-tiling',
    year: 1995,
    description: 'A dynamic composition that explores how geometric patterns can expand and evolve across a canvas, creating a sense of growth and transformation.',
    medium: 'Mixed media on canvas',
    dimensions: '150 x 200 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Expanding tiling 1995, 150 x 200 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '22',
    title: 'Composition on Tuscan Oak Wood',
    slug: 'composition-on-tuscan-oak-wood',
    year: 1995,
    description: 'A three-dimensional composition created on Tuscan oak wood, exploring the relationship between geometric abstraction and the natural qualities of the wood.',
    medium: 'Mixed media on oak wood',
    dimensions: '90 x 52 x 7 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Composition on Tuscan oak wood 1995, 90 x 52 x 7 cm.png',
    featured: false,
    category: 'abstract'
  },
  {
    id: '23',
    title: 'Composition 1995',
    slug: 'composition-1995',
    year: 1995,
    description: 'A balanced geometric composition that demonstrates the artist\'s evolving style in the mid-1990s, with a refined approach to form and color.',
    medium: 'Mixed media',
    dimensions: '40 x 50 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Composition 1995, 40 x 50 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '24',
    title: 'Tuscan Tiling II',
    slug: 'tuscan-tiling-ii',
    year: 1995,
    description: 'A three-dimensional work inspired by traditional Tuscan tiling patterns, reinterpreted through contemporary sculptural form.',
    medium: 'Mixed media sculpture',
    dimensions: 'Height ca. 100 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Tuscan tiling II 1995, height ca. 100 cm.png',
    featured: false,
    category: 'abstract'
  },
  {
    id: '25',
    title: 'Tuscan Tiling I',
    slug: 'tuscan-tiling-i',
    year: 1994,
    description: 'A geometric pattern study inspired by historic Italian tiling designs, reinterpreted through a contemporary minimalist aesthetic. The work connects traditional pattern-making with modern compositional approaches.',
    medium: 'Acrylic on canvas',
    dimensions: '165 x 165 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Tuscan tiling I 1994, 165 x 165 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '26',
    title: 'Rhythmic Pattern',
    slug: 'rhythmic-pattern',
    year: 1994,
    description: 'A composition exploring visual rhythm through repeating geometric forms and a carefully balanced color palette.',
    medium: 'Mixed media',
    dimensions: '60 x 40 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Rhythmic pattern 1994, 60 x 40 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '27',
    title: 'Made in Montescudaio',
    slug: 'made-in-montescudaio',
    year: 1994,
    description: 'A small-scale work created during the artist\'s time in Montescudaio, Italy, reflecting the influence of the Tuscan environment on his geometric language.',
    medium: 'Mixed media',
    dimensions: '25 x 20 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Made in Montescudaio 1994, 25 x 20 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '28',
    title: 'Two Worlds',
    slug: 'two-worlds',
    year: 1993,
    description: 'A composition that explores the concept of duality through contrasting visual languages within a single canvas.',
    medium: 'Mixed media on canvas',
    dimensions: '120 x 170 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Two worlds 1993, 120 x 170 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '29',
    title: 'Changing Pattern with Escape',
    slug: 'changing-pattern-with-escape',
    year: 1994,
    description: 'A composition that explores the concept of pattern disruption and visual escape through a carefully structured geometric language.',
    medium: 'Mixed media',
    dimensions: '40 x 50 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Changing pattern with escape 1994, 40 x 50 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '30',
    title: 'Composition with Tax Papers from Montescudaio',
    slug: 'composition-with-tax-papers-from-montescudaio',
    year: 1994,
    description: 'A mixed media composition incorporating tax documents from Montescudaio, Italy, creating a dialogue between bureaucratic materials and artistic expression.',
    medium: 'Mixed media with tax papers',
    dimensions: '40 x 30 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Composition with tax papers from Montescudaio 1994, 40 x 30 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '31',
    title: 'Montescudaio',
    slug: 'montescudaio',
    year: 1994,
    description: 'A composition inspired by the artist\'s time in the Tuscan town of Montescudaio, reflecting the visual rhythms and structures of the Italian landscape.',
    medium: 'Mixed media',
    dimensions: '60 x 40 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Montescudaio 1994,60 x 40 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '32',
    title: 'Quasi Symmetrical Scene Based on Basic Unit',
    slug: 'quasi-symmetrical-scene-based-on-basic-unit',
    year: 1992,
    description: 'A large-scale composition exploring the concept of near-symmetry through variations on a basic geometric unit, creating a complex visual field that rewards extended viewing.',
    medium: 'Mixed media on canvas',
    dimensions: '240 x 160 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Quasi symmetrical scene based on basic unit 1992, 240 x 160 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '33',
    title: 'Changing Pattern Variations',
    slug: 'changing-pattern-variations',
    year: 1991,
    description: 'A study of pattern transformations across a defined field, with subtle variations in color and form creating a sense of visual rhythm and progression.',
    medium: 'Mixed media on canvas',
    dimensions: '150 x 150 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Changing pattern variations 1991, 150 x 150 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '34',
    title: 'Changing Pattern with Opening II',
    slug: 'changing-pattern-with-opening-ii',
    year: 1991,
    description: 'A continuation of the artist\'s exploration of pattern interruption, with a more complex arrangement of forms and a larger scale that creates a more immersive viewing experience.',
    medium: 'Mixed media on canvas',
    dimensions: '150 x 200 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Changing pattern with opening II 1991, 150 x 200 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '35',
    title: 'Changing Pattern with Opening I',
    slug: 'changing-pattern-with-opening-i',
    year: 1990,
    description: 'A geometric composition featuring a central opening that interrupts an evolving pattern, creating a focal point that draws the viewer into the composition.',
    medium: 'Mixed media on canvas',
    dimensions: '90 x 95 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Changing pattern with opening I 1990, 90 x 95 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '36',
    title: 'Division of the Surface Hard - Soft',
    slug: 'division-of-the-surface-hard-soft',
    year: 1990,
    description: 'A composition exploring the contrast between hard and soft visual elements, creating a dynamic tension across the surface of the canvas.',
    medium: 'Mixed media on canvas',
    dimensions: '120 x 100 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Division of the surface hard - soft 1990, 120 x 100 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '37',
    title: 'Changing Pattern with Relief II',
    slug: 'changing-pattern-with-relief-ii',
    year: 1990,
    description: 'A larger-scale exploration of textured pattern variations, with more complex relief elements creating a richer interplay of light and shadow across the composition.',
    medium: 'Mixed media on panel',
    dimensions: '150 x 150 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Changing pattern with relief II 1990, 150 x 150 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '38',
    title: 'Changing Pattern with Relief I',
    slug: 'changing-pattern-with-relief-i',
    year: 1990,
    description: 'A textured work exploring pattern variations with dimensional relief elements that create visual complexity through shadows and form. The interplay of light across the relief surface creates an ever-changing visual experience.',
    medium: 'Mixed media on panel',
    dimensions: '100 x 100 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Changing pattern with relief I 1990, 100 x 100 cm.jpg',
    featured: true,
    category: 'abstract'
  },
  {
    id: '39',
    title: 'Changing Tiling on a Wooden Plank',
    slug: 'changing-tiling-wooden-plank',
    year: 1990,
    description: 'An elongated composition exploring the gradual transformation of geometric patterns across a horizontal plane. The work invites the viewer to observe how patterns evolve and interact across the composition.',
    medium: 'Mixed media on wood',
    dimensions: '60 x 200 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Changing tiling on a wooden plank 1990, 60 x 200 cm.png',
    featured: false,
    category: 'abstract'
  },
  {
    id: '40',
    title: 'Tiling with Handwritings',
    slug: 'tiling-with-handwritings',
    year: 1997,
    description: 'A composition that integrates calligraphic elements with geometric tiling patterns, exploring the relationship between written language and abstract visual form.',
    medium: 'Mixed media on canvas',
    dimensions: '135 x 145 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Tiling with handwritings 1997, 135 x 145 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '41',
    title: 'Division of the Plane with Unequal Units',
    slug: 'division-of-the-plane-with-unequal-units',
    year: 1996,
    description: 'An exploration of spatial division using unequal geometric units, creating a dynamic tension between symmetry and asymmetry across the composition.',
    medium: 'Mixed media on canvas',
    dimensions: '180 x 180 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Division of the plane with unequal units 1996, 180 x 180 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  {
    id: '42',
    title: 'Division of the Plane with Stamps',
    slug: 'division-of-the-plane-with-stamps',
    year: 1997,
    description: 'A mixed media composition that incorporates postage stamps as visual elements, creating a dialogue between official documentation and artistic expression.',
    medium: 'Mixed media with stamps',
    dimensions: '65 x 65 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Division of the plane with stamps 1997, 65 x 65 cm.jpg',
    featured: false,
    category: 'abstract'
  },
  // Paper artworks
  {
    id: '108',
    title: 'Souvenir pentagonale de Roustchouk',
    slug: 'souvenir-pentagonale-de-roustchouk',
    year: 2024,
    description: 'Old stock paper from 1895 on canvas, acrylic paint with Arabic gum. Both inside the stock paper as well as outside the paper, an interesting pentagonal rotating pattern can be observed.',
    medium: 'Old stock paper on canvas, acrylic with Arabic gum',
    dimensions: '50 x 70 cm',
    imagePath: '/2024/Banque_Bulgare_De_Commerce_a_Roustchouk 50x70cm_2024.png',
    featured: true,
    category: 'paper'
  },
  {
    id: '109',
    title: 'Souvenir de Roustchouk à la Asmat',
    slug: 'souvenir-de-roustchouk-a-la-asmat',
    year: 2024,
    description: 'Old stock paper from 1895 on canvas, acrylic paint with Arabic gum. On the inside an intriguing pattern is present derived from an Asmat shield. Outside the paper other Asmat patterns are visible, derived from a shield and a canoe model, with additional colored dots.',
    medium: 'Old stock paper on canvas, acrylic with Arabic gum',
    dimensions: '50 x 70 cm',
    imagePath: '/2024/banque_Bulgare_De_Commerce_1895_Roustchouk 2024 50x70cm other_version.png',
    featured: true,
    category: 'paper'
  },
  {
    id: '43',
    title: 'Aandeelkunstwerk Donetz',
    slug: 'aandeelkunstwerk-donetz-2019',
    year: 2019,
    description: 'A mixed media artwork incorporating historical stock certificates from the Donetz region, exploring themes of economic history, value, and cultural memory.',
    medium: 'Mixed media with stock certificates',
    dimensions: 'Variable',
    imagePath: '/Old stock paper Artworks 2005 - 20/Aandeelkunstwerk Donetz  24-01-2019.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '44',
    title: 'Aandeelkunstwerk Donetz II',
    slug: 'aandeelkunstwerk-donetz-ii-2019',
    year: 2019,
    description: 'A second exploration of the Donetz stock certificates, with a different compositional approach that highlights different aspects of the historical documents.',
    medium: 'Mixed media with stock certificates',
    dimensions: 'Variable',
    imagePath: '/Old stock paper Artworks 2005 - 20/Aandeelkunstwerk Donetz IMG_5738 24-01-2019.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '45',
    title: 'Nieuw Werk',
    slug: 'nieuw-werk-2018',
    year: 2018,
    description: 'A new work exploring the artist\'s ongoing interest in historical documents and their recontextualization as contemporary art objects.',
    medium: 'Mixed media on paper',
    dimensions: 'Variable',
    imagePath: '/Old stock paper Artworks 2005 - 20/Nieuw werk Nov-2018.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '46',
    title: 'Chemin de Fer-Lung-Tsing-U-Haï No. 3',
    slug: 'chemin-de-fer-lung-tsing-u-hai-no-3',
    year: 2018,
    description: 'The third in a series exploring historical railway documentation from China, continuing the artist\'s investigation of cultural exchange and colonial history.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Chemin de Fer-Lung-Tsing-U-Haï No. 3 2018, 40 x 50 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '47',
    title: 'Aandeelkunstwerk Belge',
    slug: 'aandeelkunstwerk-belge',
    year: 2017,
    description: 'A mixed media composition incorporating Belgian stock certificates, exploring themes of economic history and the visual language of financial documents.',
    medium: 'Mixed media with stock certificates',
    dimensions: 'Variable',
    imagePath: '/Old stock paper Artworks 2005 - 20/Aandeelkunstwerk Belge IMG_5244 8 juni 2017.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '48',
    title: 'Society Hellénique Anonyme (1)',
    slug: 'society-hellenique-anonyme-1',
    year: 2017,
    description: 'A composition incorporating Greek stock certificates, exploring the visual language of financial documents and their cultural significance.',
    medium: 'Mixed media with stock certificates',
    dimensions: '34 x 22 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Society Hellénique Anonyme 2017 (1), 34 x 22 cm.png',
    featured: false,
    category: 'paper'
  },
  {
    id: '49',
    title: 'Society Hellénique Anonyme (2)',
    slug: 'society-hellenique-anonyme-2',
    year: 2017,
    description: 'A companion piece to Society Hellénique Anonyme (1), offering a different perspective on the same historical materials.',
    medium: 'Mixed media with stock certificates',
    dimensions: '34 x 22 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Society Hellénique Anonyme 2017 (2), 34 x 22 cm.png',
    featured: false,
    category: 'paper'
  },
  {
    id: '50',
    title: 'La Franco-Belge Fluviale',
    slug: 'la-franco-belge-fluviale',
    year: 2017,
    description: 'A mixed media work incorporating historical documents related to Franco-Belgian river transport, exploring themes of cross-border commerce and shared waterways.',
    medium: 'Mixed media on paper',
    dimensions: '23.2 x 35 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/La Franco-Belge Fluviale 2017, 23.2 x 35 cm.png',
    featured: false,
    category: 'paper'
  },
  {
    id: '51',
    title: 'Société Minière & Industrielle du Tamega',
    slug: 'societe-miniere-industrielle-du-tamega',
    year: 2017,
    description: 'A composition incorporating historical documents from the Tamega mining and industrial company, exploring themes of resource extraction and industrial development.',
    medium: 'Mixed media on paper',
    dimensions: '20.4 x 27.8 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Société Minière & Industrielle du Tamega 2017, 20.4 x 27.8 cm.png',
    featured: false,
    category: 'paper'
  },
  {
    id: '52',
    title: 'Miro for sale for Eén Duizend Gulden',
    slug: 'miro-for-sale',
    year: 2017,
    description: 'A playful work that references both the art market and the visual language of Miró, incorporating historical currency and financial documents.',
    medium: 'Mixed media on paper',
    dimensions: '13.8 x 25 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Miro for sale for Eén Duizend Gulden 2017, 13.8 x 25 cm.png',
    featured: false,
    category: 'paper'
  },
  {
    id: '53',
    title: 'Harmen & Izabella',
    slug: 'harmen-izabella',
    year: 2015,
    description: 'A commemorative work celebrating Harmen and Izabella, incorporating personal documents and memorabilia into a mixed media composition.',
    medium: 'Mixed media on paper',
    dimensions: '45 x 35 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Harmen & Izabella 1 August 2015, 45 x 35 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '54',
    title: 'François Rive 60',
    slug: 'francois-rive-60',
    year: 2015,
    description: 'A commemorative work celebrating François Rive\'s 60th birthday, incorporating personal documents and memorabilia into a mixed media composition.',
    medium: 'Mixed media on paper',
    dimensions: '30 x 40 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/François Rive 60, 2015, 30 x 40 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '55',
    title: 'Chemin de Fer Lung-Tsing-U-Haï No. 2',
    slug: 'chemin-de-fer-lung-tsing-u-hai-no-2',
    year: 2014,
    description: 'A continuation of the artist\'s exploration of historical railway documentation, with a more complex integration of archival materials and contemporary artistic elements.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Chemin de Fer Lung-Tsing-U-Haï No. 2 2014, 40 x 50 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '56',
    title: 'Les Tramways d\'Iékaterinoslaw',
    slug: 'tramways-iekaterinoslaw',
    year: 2013,
    description: 'Part of the tram series, this work documents and artistically interprets the historic tram systems of Eastern Europe, combining documentary and aesthetic approaches.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: "/Old stock paper Artworks 2005 - 20/Les Tramways katerino 2013, 40 x 50 cm.jpg",
    featured: true,
    category: 'paper'
  },
  {
    id: '57',
    title: 'Les Tramways de Kiew 2013',
    slug: 'les-tramways-de-kiew-2013',
    year: 2013,
    description: 'Part of the urban transit documentation series, this work captures the iconic tram systems of Kiev through a combination of historical documents and artistic interpretation.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Les Tramways de Kiew 2013, 40 x 50 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '58',
    title: 'Cepir-344 Russian Stock Paper',
    slug: 'cepir-344-russian-stock-paper',
    year: 2012,
    description: 'A composition incorporating Russian stock certificates from 1906, exploring the visual language of financial documents and their historical context.',
    medium: 'Mixed media with stock certificates',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Cepir-344 . Russian stock paper 1906) 2012, 40 x 50 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '59',
    title: 'Les Tramways de Kiew 2011',
    slug: 'les-tramways-de-kiew-2011',
    year: 2011,
    description: 'An earlier exploration of the Kiev tram system, with a different compositional approach than the 2013 version.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Les Tramways de Kiew 2011, 40 x 50 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '60',
    title: 'Gabrielle Hurwitz 60',
    slug: 'gabrielle-hurwitz-60',
    year: 2011,
    description: 'A commemorative work celebrating Gabrielle Hurwitz\'s 60th birthday, incorporating personal documents and memorabilia into a mixed media composition.',
    medium: 'Mixed media on paper',
    dimensions: '20 x 30 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Gabrielle Hurwitz 60 2011, 20 x 30 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '61',
    title: 'Tramways d\'Odessa II',
    slug: 'tramways-odessa-ii',
    year: 2008,
    description: 'A continuation of the artist\'s exploration of the Odessa tram system, with a more complex integration of historical documentation and artistic interpretation.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: "/Old stock paper Artworks 2005 - 20/Tramways odessa2 2008, 40 x 50 cm.jpg",
    featured: false,
    category: 'paper'
  },
  {
    id: '62',
    title: 'Tramways de Saratov',
    slug: 'tramways-de-saratov',
    year: 2008,
    description: 'Part of the tram series, this work documents and artistically interprets the historic tram system of Saratov, Russia.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Tramways de Saratov 2008, 40 x 50 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '63',
    title: 'Société d\'Etudes des Entreprises Russes',
    slug: 'societe-etudes-entreprises-russes',
    year: 2007,
    description: 'A mixed media composition exploring the history of Russian industrial enterprises through archival documentation, combining historical materials with contemporary artistic interpretation.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: "/Old stock paper Artworks 2005 - 20/enterprise.jpg",
    featured: false,
    category: 'paper'
  },
  {
    id: '64',
    title: 'Mines et Usines Zinc de Silésie',
    slug: 'mines-et-usines-zinc-de-silesie',
    year: 2007,
    description: 'A mixed media work exploring the industrial heritage of zinc mining and production in Silesia, incorporating historical documents and contemporary artistic elements.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Mines et Usines Zinc de Silésie 2007, 40 x 50 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '65',
    title: 'Briqueteries & Tuileries Mécaniques de Saint Léonard',
    slug: 'briqueteries-tuileries-mecaniques',
    year: 2007,
    description: 'A mixed media work exploring the industrial heritage of brick and tile manufacturing, combining historical documentation with artistic interpretation.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Briqueteries & Tuileries Mécaniques de SaintLéonard 2007, 40 x 50 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '66',
    title: 'Société d\'Électricité d\'Odessa',
    slug: 'societe-electricite-odessa',
    year: 2006,
    description: 'A mixed media work exploring the industrial heritage of Odessa through historical documentation of its electrical infrastructure, combining archival materials with contemporary artistic expression.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: "/Old stock paper Artworks 2005 - 20/electricity.jpg",
    featured: false,
    category: 'paper'
  },
  {
    id: '67',
    title: 'Tramways d\'Odessa I',
    slug: 'tramways-odessa-i',
    year: 2005,
    description: 'A mixed media composition documenting the historic tram system of Odessa, integrating historical imagery with contemporary artistic expression.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Tramways d\'Odessa I 2005, 40 x 50 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '68',
    title: 'Fabrication des Bouteilles à Odessa I',
    slug: 'fabrication-bouteilles-odessa-i',
    year: 2005,
    description: 'A mixed media work that explores industrial heritage and manufacturing processes in Odessa, combining historical documentation with artistic interpretation.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Fabrication des Bouteilles à Odessa I 2005, 40 x 50 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '69',
    title: 'Fabrication des Bouteilles à Odessa II',
    slug: 'fabrication-bouteilles-odessa-ii',
    year: 2005,
    description: 'A continuation of the artist\'s exploration of bottle manufacturing in Odessa, with a different compositional approach to the integration of historical documentation and artistic interpretation.',
    medium: 'Mixed media on paper',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Fabrication des Bouteilles à Odessa II 2005, 40 x 50 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '70',
    title: 'Chemin de Fer Lung-Tsing-U-Haï',
    slug: 'chemin-de-fer-lung-tsing-u-hai',
    year: 2005,
    description: 'A mixed media composition integrating archival materials with contemporary artistic elements, exploring themes of travel, cultural exchange, and historical memory.',
    medium: 'Mixed media collage',
    dimensions: '40 x 50 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Chemin de Fer Lung-Tsing-U-Haï 2005, 40 x 50 cm.jpg',
    featured: true,
    category: 'paper'
  },
  {
    id: '71',
    title: 'Les tramways de Kiew DMB60',
    slug: 'les-tramways-de-kiew-dmb60',
    year: 2005,
    description: 'An early exploration of the Kiev tram system, with a focus on the DMB60 line, combining historical documentation with artistic interpretation.',
    medium: 'Mixed media on paper',
    dimensions: '30 x 20 cm',
    imagePath: '/Old stock paper Artworks 2005 - 20/Les tramways de Kiew DMB60 2005, 30 x 20 cm.jpg',
    featured: false,
    category: 'paper'
  },
  {
    id: '38',
    title: 'Loterij mei 1870 met Frank Lodeizen',
    slug: 'loterij-mei-1870-frank-lodeizen',
    year: 2021,
    description: 'Artwork incorporating historical lottery ticket from May 1870, featuring elements related to Frank Lodeizen.',
    medium: 'Mixed media on paper',
    dimensions: 'Dimensions not specified',
    imagePath: '/Old stock paper Artworks 2005 - 20/Loterij mei 1870 met Frank Lodeizen IMG_6772.png',
    featured: false,
    category: 'paper'
  },
  {
    id: '39',
    title: 'Grieks Aandeelkunstwerk Oktober 2022',
    slug: 'grieks-aandeelkunstwerk-oktober-2022',
    year: 2022,
    description: 'Artwork based on a Greek share certificate, created in October 2022.',
    medium: 'Mixed media on paper',
    dimensions: 'Dimensions not specified',
    imagePath: '/Old stock paper Artworks 2005 - 20/Grieks aandeelkunstwerk 1 okt 2022 IMG_6403.png',
    featured: false,
    category: 'paper'
  },
  // James Joyce Artworks
  {
    id: '72',
    title: 'James Joyce',
    slug: 'james-joyce',
    year: 2004,
    description: 'A portrait of the iconic modernist writer that explores the relationship between visual and literary expression, capturing Joyce\'s innovative approach to language and narrative.',
    medium: 'Mixed media',
    dimensions: '41 x 20 cm',
    imagePath: '/James Joyce Artworks/James Joyce 2004, 41 x 20 cm.jpg',
    featured: false,
    category: 'joyce'
  },
  {
    id: '73',
    title: 'James Joyce & Dublin',
    slug: 'james-joyce-dublin',
    year: 2007,
    description: 'A work that explores the relationship between the iconic writer and the city that shaped his literary vision, combining portraiture with urban imagery to create a rich visual narrative.',
    medium: 'Mixed media',
    dimensions: '41 x 29 cm',
    imagePath: '/James Joyce Artworks/James-Joyce-&-Dublin-2007,-41-x-29-cm.jpg',
    featured: false,
    category: 'joyce'
  },
  {
    id: '74',
    title: 'Portrait of James Joyce',
    slug: 'portrait-of-james-joyce-1998',
    year: 1998,
    description: 'A contemplative portrait of the modernist writer that captures his distinctive features and intellectual intensity through a combination of representational and expressive elements.',
    medium: 'Mixed media',
    dimensions: '40 x 50 cm',
    imagePath: '/James Joyce Artworks/Portrait of James Joyce 1998, 40 x 50 cm.jpg',
    featured: false,
    category: 'joyce'
  },
  {
    id: '75',
    title: 'Portrait of James Joyce',
    slug: 'portrait-of-james-joyce-1985',
    year: 1985,
    description: 'An early portrait study of James Joyce that demonstrates the artist\'s developing interest in literary figures and their visual representation.',
    medium: 'Mixed media',
    dimensions: '22 x 29 cm',
    imagePath: '/James Joyce Artworks/Portret of James Joyce 1985, 22 x 29 cm.jpg',
    featured: false,
    category: 'joyce'
  },
  
  // Figurative Artworks 1980-1989
  {
    id: '76',
    title: 'Egyptian Scene with Depth',
    slug: 'egyptian-scene-with-depth',
    year: 1985,
    description: 'A composition inspired by Egyptian artistic conventions but reinterpreted with spatial depth and dimensional perspective. This work represents an early exploration of how traditional visual languages can be reinterpreted through contemporary approaches.',
    medium: 'Oil on canvas',
    dimensions: '125 x 90 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Egyptian scene, with depth 1985, 125 x 90 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '77',
    title: 'Egyptian Scene Flat',
    slug: 'egyptian-scene-flat',
    year: 1984,
    description: 'A study of Egyptian visual language that maintains the traditional flatness of Egyptian art while introducing contemporary elements. This work reflects the artist\'s early interest in ancient aesthetic systems and their potential for contemporary expression.',
    medium: 'Oil on canvas',
    dimensions: '120 x 85 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Egyptian scene, flat 1984, 120 x 85 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '78',
    title: 'Egyptian Klee Girl',
    slug: 'egyptian-klee-girl',
    year: 1985,
    description: 'A figurative work that combines Egyptian visual conventions with the playful linear approach of Paul Klee, creating a cross-cultural dialogue between ancient and modern artistic languages.',
    medium: 'Oil on canvas',
    dimensions: '140 x 60 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Egyptian Klee girl 1985, 140 x 60 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '79',
    title: 'Portrait of Mondrian',
    slug: 'portrait-of-mondrian',
    year: 1985,
    description: 'A portrait that reinterprets the iconic Dutch modernist through a contemporary lens, exploring the relationship between figuration and abstraction that characterized Mondrian\'s own artistic journey.',
    medium: 'Oil on canvas',
    dimensions: '100 x 100 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Portrait of Mondrian 1985, 100 x 100 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '80',
    title: 'Mondrian Skies',
    slug: 'mondrian-skies',
    year: 1985,
    description: 'A landscape-inspired composition that applies Mondrian\'s geometric principles to atmospheric phenomena, creating a dialogue between natural forms and abstract structural elements.',
    medium: 'Oil on canvas',
    dimensions: '150 x 200 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Mondrian skies 1985, 150 x 200 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '81',
    title: 'Portrait of Nietzsche',
    slug: 'portrait-of-nietzsche',
    year: 1985,
    description: 'A portrait of the influential philosopher that captures both his physical likeness and suggests the intensity of his intellectual vision through expressive brushwork and compositional elements.',
    medium: 'Oil on canvas',
    dimensions: '60 x 60 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Portrait of Nietzsche 1985, 60 x 60 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '82',
    title: 'The Memorial',
    slug: 'the-memorial',
    year: 1987,
    description: 'A complex figurative composition that explores themes of memory, history, and commemoration through a richly detailed visual narrative.',
    medium: 'Oil on canvas',
    dimensions: '150 x 180 cm',
    imagePath: '/Figurative Artworks 1980 -1989/The memorial 1987, 150-x 180 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '83',
    title: 'Portrait of Simon Vestdijk',
    slug: 'portrait-of-simon-vestdijk',
    year: 1985,
    description: 'A portrait of the renowned Dutch writer that captures his distinctive features and intellectual character through a combination of representational and expressive elements.',
    medium: 'Oil on canvas',
    dimensions: '22 x 29 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Portrait-of-Simon-Vestdijk-1985,-22-x-29-cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '84',
    title: 'Infinity',
    slug: 'infinity',
    year: 1985,
    description: 'A figurative work that explores the concept of infinity through symbolic visual elements and spatial relationships.',
    medium: 'Oil on canvas',
    dimensions: '65 x 65 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Infinity 1985, 65 x 65 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '85',
    title: 'Labyrinth',
    slug: 'labyrinth',
    year: 1985,
    description: 'A figurative composition that explores the concept of the labyrinth as both a physical structure and a metaphor for psychological complexity.',
    medium: 'Oil on canvas',
    dimensions: '50 x 40 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Labyrinth 1985, 50 x 40 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '86',
    title: 'Two Playing Dogs',
    slug: 'two-playing-dogs',
    year: 1985,
    description: 'A playful figurative work that captures the dynamic movement and interaction of two dogs at play, rendered with expressive brushwork and a lively color palette.',
    medium: 'Oil on canvas',
    dimensions: '36 x 28 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Two playing dogs 1985, 36 x 28 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '87',
    title: 'Underwater Scenery',
    slug: 'underwater-scenery',
    year: 1986,
    description: 'A figurative composition that explores the visual and atmospheric qualities of an underwater environment, with a dreamlike quality that blends representational and abstract elements.',
    medium: 'Oil on canvas',
    dimensions: '200 x 150 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Underwater scenery 1986, 200 x 150 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '88',
    title: 'Tragic Paul Klee Scenery',
    slug: 'tragic-paul-klee-scenery',
    year: 1985,
    description: 'A figurative work inspired by the visual language of Paul Klee, but with a darker, more tragic emotional tone that creates a powerful psychological atmosphere.',
    medium: 'Oil on canvas',
    dimensions: '120 x 90 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Tragic Paul Klee scenery 1985, 120 x 90 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '102',
    title: 'Mondrian',
    slug: 'mondrian-1980',
    year: 1980,
    description: 'An early work exploring the geometric principles and visual language of Mondrian, demonstrating the artist\'s interest in modernist abstraction and its relationship to figurative elements.',
    medium: 'Oil on canvas',
    dimensions: '70 x 80 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Mondrian-1980, 70 x 80 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '103',
    title: 'Portrait of a Man No.1',
    slug: 'portrait-of-a-man-no-1',
    year: 1985,
    description: 'A figurative portrait that explores the human form through a combination of representational and expressive elements, capturing both physical likeness and psychological presence.',
    medium: 'Oil on canvas',
    dimensions: '50 x 90 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Portrait of a man No.1 1985, 50 x 90 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '104',
    title: 'Portrait of a Man No.2',
    slug: 'portrait-of-a-man-no-2',
    year: 1985,
    description: 'A companion piece to Portrait of a Man No.1, offering a different approach to portraiture with a focus on different aspects of the subject\'s character and presence.',
    medium: 'Oil on canvas',
    dimensions: '45 x 60 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Portrait of a man No.2 1985, 45 x 60 cm.jpg',
    featured: false,
    category: 'figurative'
  },
  {
    id: '105',
    title: 'Scenery with Hippo According to Agnes de G.',
    slug: 'scenery-with-hippo-according-to-agnes-de-g',
    year: 1986,
    description: 'A whimsical figurative composition featuring a hippo in a landscape setting, inspired by or dedicated to Agnes de G., combining playful elements with sophisticated compositional structure.',
    medium: 'Oil on canvas',
    dimensions: '120 x 120 cm',
    imagePath: '/Figurative Artworks 1980 -1989/Scenery with hippo according to Agnes de G. 1986, 120 x 120.jpg',
    featured: false,
    category: 'figurative'
  },
  
  // Other Artworks
  {
    id: '89',
    title: 'Conversation at Three Levels 1994',
    slug: 'conversation-at-three-levels-1994',
    year: 1994,
    description: 'A composition exploring multi-layered communication through visual elements arranged at different levels, creating a sense of dialogue between forms.',
    medium: 'Mixed media',
    dimensions: '24 x 30 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Conversation at three levels 1994, 24 x 30 cm.jpg',
    featured: false,
    category: 'other'
  },
  {
    id: '90',
    title: 'Birth of Victor',
    slug: 'birth-of-victor',
    year: 2000,
    description: 'A celebratory work commemorating the birth of Victor, combining personal symbolism with abstract elements to create a visual narrative of new life.',
    medium: 'Mixed media',
    dimensions: '12 x 27 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Birth of Victor, 2000, 12 x 27 cm.jpg',
    featured: false,
    category: 'other'
  },
  {
    id: '91',
    title: 'Ancient Hand Writing',
    slug: 'ancient-hand-writing',
    year: 1997,
    description: 'A work inspired by ancient calligraphic traditions, exploring the visual qualities of handwritten text as abstract form and cultural artifact.',
    medium: 'Mixed media',
    dimensions: '42 x 30 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Ancient hand writing 1997, 42 x 30 cm.png',
    featured: false,
    category: 'other'
  },
  {
    id: '92',
    title: 'Kufic Writing',
    slug: 'kufic-writing',
    year: 1997,
    description: 'A composition inspired by the angular, geometric qualities of Kufic script, exploring the intersection of language, visual form, and cultural heritage.',
    medium: 'Mixed media',
    dimensions: '40 x 30 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Kufic writing 1997, 40 x 30 cm.png',
    featured: false,
    category: 'other'
  },
  {
    id: '93',
    title: 'Arabic Message',
    slug: 'arabic-message',
    year: 1997,
    description: 'A work that incorporates elements of Arabic calligraphy, exploring the expressive and aesthetic qualities of script as both communication and visual art.',
    medium: 'Mixed media',
    dimensions: '29 x 41 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Arabic message 1997, 29 x 41 cm.png',
    featured: false,
    category: 'other'
  },
  {
    id: '94',
    title: 'Metropolis',
    slug: 'metropolis',
    year: 1997,
    description: 'A large-scale composition exploring urban structures and the visual rhythms of city life, with layered geometric forms suggesting architectural complexity.',
    medium: 'Mixed media on canvas',
    dimensions: '120 x 80 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Metropolis 1997, 120 x 80 cm.jpg',
    featured: false,
    category: 'other'
  },
  {
    id: '95',
    title: 'Conversation at Three Levels 1997',
    slug: 'conversation-at-three-levels-1997',
    year: 1997,
    description: 'A further exploration of multi-layered communication, developing the themes of the 1994 work with greater complexity and a more refined visual language.',
    medium: 'Mixed media',
    dimensions: '35 x 45 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Conversation at three levels 1997, 35 x 45 cm.jpg',
    featured: false,
    category: 'other'
  },
  {
    id: '96',
    title: 'Portrait',
    slug: 'portrait-1994',
    year: 1994,
    description: 'An abstract interpretation of portraiture that explores the essence of identity through geometric form and expressive color rather than literal representation.',
    medium: 'Mixed media',
    dimensions: '30 x 40 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Portrait 1994, 30 x 40 cm.jpg',
    featured: false,
    category: 'other'
  },
  {
    id: '97',
    title: 'Four Painted Heads on Gin Bottle',
    slug: 'four-painted-heads-on-gin-bottle',
    year: 1994,
    description: 'A three-dimensional work featuring four painted heads arranged around a gin bottle, creating a sculptural object that can be viewed from multiple perspectives.',
    medium: 'Paint on glass',
    dimensions: 'ca. 7 x 16 cm on 4 sides',
    imagePath: '/Large abstract Artworks 1990 - 20/Four painted heads on gin bottle 1994, ca. 7 x 16 cm on 4 sides.jpg',
    featured: false,
    category: 'other'
  },
  {
    id: '98',
    title: 'Four Changing Patterns on Gin Bottle',
    slug: 'four-changing-patterns-on-gin-bottle',
    year: 1994,
    description: 'A three-dimensional work featuring four evolving patterns painted around a gin bottle, creating a dynamic visual experience as the viewer moves around the object.',
    medium: 'Paint on glass',
    dimensions: 'ca. 6 x 12 cm on 4 sides',
    imagePath: '/Large abstract Artworks 1990 - 20/Four changing patterns on gin bottle 1994, ca. 6 x 12 cm on 4 sides.jpg',
    featured: false,
    category: 'other'
  },
  {
    id: '99',
    title: 'Four Portraits on Gin Bottle',
    slug: 'four-portraits-on-gin-bottle',
    year: 1994,
    description: 'A three-dimensional work featuring four portrait studies painted around a gin bottle, exploring the relationship between two-dimensional representation and three-dimensional form.',
    medium: 'Paint on glass',
    dimensions: 'ca. 6 x 20 cm on 4 sides',
    imagePath: '/Large abstract Artworks 1990 - 20/Four portraits on gin bottle 1994, ca. 6 x 20 cm on 4 sides.jpg',
    featured: false,
    category: 'other'
  },
  {
    id: '100',
    title: 'Small Composition 2017',
    slug: 'small-composition-2017',
    year: 2017,
    description: 'A miniature geometric composition on linen cloth, demonstrating the artist\'s ability to create balanced and sophisticated visual relationships on a small scale.',
    medium: 'Acrylic on piece of linen cloth',
    dimensions: 'about 10 x 24 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Small Composition 2017, acryl on piece of linen cloth, about 10 x 24 cm.jpg',
    featured: false,
    category: 'other'
  },
  {
    id: '101',
    title: 'Strange Unidentified Flying Object',
    slug: 'strange-unidentified-flying-object',
    year: 2014,
    description: 'A playful composition that explores the concept of the unknown through abstract geometric forms suggesting an otherworldly presence.',
    medium: 'Mixed media',
    dimensions: '40 x 50 cm',
    imagePath: '/Large abstract Artworks 1990 - 20/Strange unidentified flying object  2014, 40 x 50 cm.jpg',
    featured: false,
    category: 'other'
  }
];
